name = "reservation"
compatibility_date = "2026-02-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "reservation"
database_id = "32fd87bf-42bd-4c69-bacd-e2dbf9bfcb65"
